sudo: required

lang: bash

services:
  - docker

before_install:
  - docker build -t lixinio/sentry:9.0 .

script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push lixinio/sentry:9.0
